#!/usr/bin/env python3
"""
generate_golden.py — Auto-generate golden GEMM output from test matrices.

Reads INT8 A[16][16] and B[16][16] matrices (defined in the Python source
itself, matching the ones in firmware_gemm.c / firmware_e2e.c .rodata),
computes golden = A @ B with INT16 accumulator, and emits a C header
fragment that firmware can #include.

Usage:
    python3 generate_golden.py --header > build/golden_gemm.h
    python3 generate_golden.py --json            (for cocotb consumption)
"""

import sys
import json
import struct

# ---- Test matrices — must match firmware .rodata exactly ----------
# A[i][j] = (i + j) % 7 - 3    (row-major)
# B[i][j] = (i * 3 + j) % 7 - 3


def _make_A():
    a = [[0] * 16 for _ in range(16)]
    for i in range(16):
        for j in range(16):
            a[i][j] = (i + j) % 7 - 3
    return a


def _make_B():
    b = [[0] * 16 for _ in range(16)]
    for i in range(16):
        for j in range(16):
            b[i][j] = (i * 3 + j) % 7 - 3
    return b


def compute_golden():
    """C[i][j] = sum_k A[i][k] * B[k][j]  (INT16 accumulator)."""
    A = _make_A()
    B = _make_B()
    golden = []
    for i in range(16):
        for j in range(16):
            acc = 0
            for k in range(16):
                acc += A[i][k] * B[k][j]
            golden.append(acc)
    return golden


def emit_c_header(golden):
    """Emit a standard C header fragment with static const golden_C[256]."""
    lines = []
    lines.append("// Auto-generated by tools/codegen/generate_golden.py")
    lines.append("// Golden: C = A x B  (INT8 A[16][16] @ B[16][16] → INT16)")
    lines.append("")
    lines.append("#ifndef GOLDEN_GEMM_H")
    lines.append("#define GOLDEN_GEMM_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("static const int16_t golden_C[256] __attribute__((aligned(4))) = {")
    for i, val in enumerate(golden):
        comma = "," if i < 255 else ""
        if i % 8 == 0:
            lines.append(f"    {val:5d}{comma}")
        else:
            lines[-1] += f" {val:5d}{comma}"
    lines.append("};")
    lines.append("")
    lines.append("#endif // GOLDEN_GEMM_H")
    lines.append("")
    return "\n".join(lines)


def emit_json(golden):
    """Emit a JSON object with test_A, test_B, golden_C (flat int lists)."""
    A = _make_A()
    B = _make_B()
    A_flat = [A[i][j] for i in range(16) for j in range(16)]
    B_flat = [B[i][j] for i in range(16) for j in range(16)]
    return json.dumps({"A": A_flat, "B": B_flat, "golden": golden}, indent=2)


def main():
    golden = compute_golden()

    if "--json" in sys.argv:
        print(emit_json(golden))
    elif "--header" in sys.argv:
        print(emit_c_header(golden))
    else:
        # Default: print both
        print(emit_c_header(golden))
        print()
        print("/* JSON (for cocotb): */")
        print("// " + emit_json(golden).replace("\n", "\n// "))


if __name__ == "__main__":
    main()
